src/app/admin/app-list/app-list.component.html
src/app/admin/app-manage/app-manage.component.html
src/app/admin/metadata/custom-node/custom-node.component.html
src/app/admin/metadata/npm-libraries/npm-libraries.component.html
src/app/admin/user-list/user-manage/user-apps/user-apps.component.html
src/app/admin/user-list/user-manage/user-teams/user-groups.component.html
src/app/home/app-manage/app-manage.component.html
src/app/home/b2b-flows-manage/node-properties/agent-selector/agent-selector.component.html
src/app/home/b2b-flows-manage/node-properties/connector-properties/connector-properties.component.html
src/app/home/b2b-flows-manage/node-properties/converter-properties/format-selector/format-selector.component.html
src/app/home/b2b-flows-manage/node-properties/function-selector/function-selector.component.html
src/app/home/b2b-flows-manage/node-properties/marketplace-selector/marketplace-selector.component.html
src/app/home/b2b-flows-manage/node-properties/service-selector/service-selector.component.html
src/app/home/b2b-flows/b2b-flows.component.html
src/app/home/bots/bots-manage/bots-manage.component.html
src/app/home/bots/bots.component.html
src/app/home/control-panel/user-group/user-group-manage/user-group-members/user-group-bots/user-group-bots.component.html
src/app/home/control-panel/user-group/user-group-manage/user-group-members/user-group-members-search/user-group-members-search.component.html
src/app/home/control-panel/user-group/user-group-manage/user-group-members/user-group-users/user-group-users.component.html
src/app/home/nano-service-listing/nano-service-listing.component.html
src/app/home/nano-service-manage/nano-service-manage.component.html
src/app/home/partner-listing/partner-listing.component.html
src/app/home/partner-onboard/partner-microflows/partner-microflows.component.html
src/app/home/partner-onboard/partner-secrets/partner-secrets.component.html
src/app/utils/data-structure-selector/data-format-selector/data-format-selector.component.html
src/app/utils/format-selector/format-selector.component.html

All the search boxes embedded inside the views/tabs seems to be broken. Had to search for the `odp-search-box` component usage and made necessary changes

DS-546 - [Author] The search bar on author screens is not working

---

src/app/home/b2b-flows/b2b-flows.component.ts

@jugnu-appveen - since on change of status, the other details like draft version remained the same, it started causing issues. Hence fetching specific flow details

Defect DS-570 fixed

---

src/app/home/logs/logs.component.ts

Defect DS-568 fixed

---

src/app/home/b2b-flows/b2b-flows.component.html
src/app/home/b2b-flows/b2b-flows.component.scss
src/app/home/b2b-flows/b2b-flows.component.ts
src/app/home/faas/faas-listing/faas-listing.component.html
src/app/home/faas/faas-listing/faas-listing.component.scss
src/app/home/faas/faas-listing/faas-listing.component.ts

Defect DS-572 fixed

---

src/app/home/b2b-flows-manage/node-properties/data-service-properties/data-service-properties.component.ts
src/app/utils/services/common.service.ts

Defect DS-591 fixed

---

src/app/home/b2b-flows-manage/b2b-flows-manage.component.html
src/app/home/b2b-flows-manage/flow-contants/flow-contants.component.html
src/app/home/b2b-flows-manage/flow-contants/flow-contants.component.ts
src/app/home/b2b-flows-manage/flow-volume-mounts/flow-volume-mounts.component.html
src/app/home/b2b-flows-manage/flow-volume-mounts/flow-volume-mounts.component.ts

Defect DS-589 fixed

---

src/app/home/api-keys/api-keys-list/api-keys-list.component.html
src/app/home/api-keys/api-keys-list/api-keys-list.component.ts

Addressed a search issue on the API keys screen where the search functionality was not working. This commit introduces logic to enable searching of API keys by their names.

DS-590 - [Author] The search box in the API keys screen is not working

---

src/app/admin/user-list/user-list.component.ts

Defect DS-583 fixed

---

src/app/home/schema-utils/global-schema-structure.pipe.ts

Defect DS-576 fixed

---

src/app/home/b2b-flows-manage/node-properties/converter-properties/converter-properties.component.ts

Similar changes for converter

---

src/app/home/b2b-flows-manage/flow-contants/flow-contants.component.ts
src/app/home/b2b-flows-manage/flow-volume-mounts/flow-volume-mounts.component.ts

Defect DS-613 fixed

---

src/app/home/b2b-flows-manage/node-properties/connector-properties/connector-properties.component.html
src/app/home/b2b-flows-manage/node-properties/connector-properties/connector-properties.component.ts

Fixing the re-open issue allowing delete in view mode

---

src/app/utils/data-structure-selector/custom-format-selector/custom-format-selector.component.ts

Adding dataPathSegs in custom format

---

src/app/home/b2b-flows-manage/node-properties/converter-properties/converter-properties.component.ts
src/app/home/b2b-flows-manage/node-properties/node-mapping/node-mapping.component.ts

Defect DS-533 fixed

---

src/app/home/b2b-flows-manage/node-properties/converter-properties/converter-properties.component.ts
src/app/home/b2b-flows-manage/node-properties/node-mapping/mapping-preset/mapping-preset.component.ts
src/app/home/b2b-flows-manage/node-properties/node-mapping/node-mapping.component.ts

Defect DS-622 fixed

---

src/app/home/b2b-flows-manage/flow-contants/flow-contants.component.html
src/app/home/b2b-flows-manage/flow-contants/flow-contants.component.ts

@jugnu-appveen - the checkmark just looked weird, so replaced it with radio buttons

Defect DS-617 fixed

---

src/app/home/b2b-flows-manage/node-properties/data-service-properties/data-service-properties.component.html
src/app/home/b2b-flows-manage/node-properties/node-data-selector/node-data-selector.component.html
src/app/home/b2b-flows-manage/node-properties/node-data-selector/node-data-selector.component.ts
src/app/home/b2b-flows-manage/node-properties/node-properties.component.html
src/app/home/b2b-flows-manage/path-properties/path-condition-creator/path-condition-creator.component.html
src/app/home/b2b-flows-manage/path-properties/path-condition-creator/path-condition-creator.component.ts
src/app/home/b2b-flows-manage/path-properties/path-properties.component.html
src/app/utils/autocomplete-on-edit/autocomplete-on-edit.component.html
src/app/utils/autocomplete-on-edit/autocomplete-on-edit.component.ts
src/app/utils/change-on-edit/change-on-edit.component.html
src/app/utils/change-on-edit/change-on-edit.component.ts

Defect DS-32 fixed

---

src/app/home/b2b-flows-manage/flow-contants/flow-contants.component.ts

Defect DS-618 fixed

---

src/app/admin/metadata/custom-node/custom-node.component.html
src/app/utils/code-editor/code-editor.component.ts

Removing edit from plugins

---

src/app/admin/metadata/custom-node/custom-node.component.ts

Defect DS-625 fixed

---

src/app/admin/user-list/user-manage/user-info/user-info.component.html
src/app/home/bots/bots-manage/bots-manage.component.html

Defect DS-632 fixed

---

src/app/home/b2b-flows-manage/node-properties/connector-properties/connector-properties.component.html
src/app/home/b2b-flows-manage/node-properties/connector-properties/connector-properties.component.ts

Defect DS-444 fixed

---

src/app/admin/app-list/app-list.component.ts

Defect DS-649 fixed

---

src/app/home/app-manage/app-manage.component.ts

Defect DS-641 fixed

---

src/app/home/app-manage/app-secrets/app-secrets.component.scss
src/app/home/app-manage/npm-libraries/npm-libraries.component.html
src/app/home/app-manage/npm-libraries/npm-libraries.component.scss

Add scrollbars to "App Variables" and "Configuration" tabs, and fix a small typo in the "Configuration" tab.

DS-664 - [App panel] Scroll bar is required under App variables and configuration tabs.

---

src/app/home/agents/agent-view/agent-view.component.html
src/app/home/agents/agent-view/agent-view.component.ts
src/app/home/agents/agents.component.html
src/app/home/agents/agents.component.ts

Defect DS-360 fixed

---

src/app/admin/user-list/user-manage/user-teams/user-groups.component.ts

Defect DS-689 fixed

---

src/app/home/b2b-flows/b2b-flows.component.html

Defect DS-672 fixed

---

src/app/home/b2b-flows-manage/node-properties/node-properties.component.ts
src/app/home/control-panel/user-group/user-group.component.ts

Changing condition for output data structure

---

src/app/home/plugins-manage/plugins-manage.component.ts

Defect DS-654 fixed

---

src/app/home/app-manage/app-secrets/app-secrets.component.ts

Introduce toaster messages for variable saving and deletion

DS-694 - [Author][App variables] Toaster msg is expected after creation/deletion of App variables

---

src/app/home/b2b-flows/b2b-flows.component.ts
src/app/home/control-panel/user/user.component.ts
src/app/utils/services/common.service.ts

Defect DS-668 fixed

---

src/app/admin/user-list/user-manage/user-teams/user-groups.component.ts
src/app/home/service-manager/service-manager.component.html
src/app/home/service-manager/service-manager.component.ts

Defect DS-658 and DS-689 fixed

---

src/app/admin/user-list/user-manage/user-manage.component.scss

Add scrollbar to the users tab under Admin panel.

DS-690 - [Admin Panel] Scroll bar is required under the users tab when we open a user through the admin panel

---

src/app/home/control-panel/user-group/user-group.component.ts

Defect DS-683 fixed

---

src/app/apps/apps.component.html
src/app/home/b2b-flows-manage/b2b-flow.service.ts
src/app/home/b2b-flows-manage/b2b-flows-manage.component.scss
src/app/home/b2b-flows-manage/b2b-flows-manage.component.ts
src/app/home/b2b-flows-manage/flow-node/flow-node.component.html
src/app/home/b2b-flows-manage/flow-node/flow-node.component.scss
src/app/home/b2b-flows-manage/node-properties/node-advanced-filter/node-advanced-filter.component.ts
src/app/utils/change-on-edit/change-on-edit.component.html

Minor changes on UI

---

src/app/home/app-manage/app-manage.component.ts

Defect DS-659 fixed

---

src/app/home/b2b-flows-manage/b2b-flow.service.ts
src/app/home/b2b-flows-manage/node-properties/connector-properties/connector-properties.component.ts
src/app/home/b2b-flows-manage/node-properties/connector-properties/kafka-connector/kafka-connector.component.html
src/app/home/b2b-flows-manage/node-properties/connector-properties/kafka-connector/kafka-connector.component.ts
src/app/home/b2b-flows-manage/node-properties/node-properties.component.html
src/app/utils/styled-text/styled-text.component.ts

Kafka node changes

---

src/app/home/b2b-flows-manage/node-properties/node-advanced-filter/node-advanced-filter.component.ts

Advanced filter issue fix

---

src/app/home/b2b-flows-manage/path-properties/path-condition-creator/path-condition-creator.component.html
src/app/home/b2b-flows-manage/path-properties/path-properties.component.html

Enhances path properties behavior in view mode by making these changes:
1. Path Name - input field is disabled
2. Path Color - color picker will not appear
3. Path Condition - value unset button will not be visible

DS-677 - [B2B] Able to remove the configured path condition in view mode

---

src/app/home/b2b-flows-manage/b2b-flow.service.ts
src/app/home/b2b-flows-manage/node-properties/connector-properties/sftp-connector/sftp-connector.component.html
src/app/home/b2b-flows-manage/node-properties/connector-properties/sftp-connector/sftp-connector.component.ts
src/app/home/b2b-flows-manage/node-properties/node-properties.component.ts
src/app/home/connectors-manage/connectors-manage.component.html

@jugnu-appveen 
let me know if there are any changes to be made, will make it once i'm back home

SFTP changes

---

src/app/admin/env-variable-config/env-variable-config.component.html
src/app/admin/env-variable-config/env-variable-config.component.scss
src/app/admin/env-variable-config/env-variable-config.component.ts

This commit introduces:
- **Extended Support for Installation Environment Variables**: Installation Environment Variables are now visible within the Environment Variables tab. However, users cannot update them via the UI/API. Configuration is exclusively through ConfigMap editing.
- Handling of ALLOWED_FILE_TYPES: An edge case is managed, replacing the input field with a more suitable text area for the `ALLOWED_FILE_TYPES` variable.
- Margin Issue Resolution: A margin issue has been fixed to ensure consistent scrolling
Updated UI

Extends support for Installation environment variables

---

src/app/home/b2b-flows-manage/b2b-flow.service.ts
src/app/home/b2b-flows-manage/b2b-flows-manage.component.html
src/app/home/b2b-flows-manage/b2b-flows-manage.component.scss
src/app/home/b2b-flows-manage/b2b-flows-manage.component.ts
src/app/home/b2b-flows-manage/flow-node/flow-node.component.html
src/app/home/b2b-flows-manage/node-properties/node-properties.component.ts
src/app/utils/view-box/view-box.directive.ts

@jugnu-appveen - UI changes for the dynamic name, errors and warnings, icon issues

Warning and errors popover

---

src/app/home/b2b-flows-manage/node-properties/node-properties.component.ts

Defect DS-751 fixed

---

src/app/home/agents/agent-view/agent-view.component.html

Defect DS-724 fixed

---

src/app/home/agents/agents.component.html
src/app/home/b2b-flows-manage/node-properties/data-service-properties/data-service-properties.component.ts

Defect DS-753 fixed

---

src/app/home/b2b-flows-manage/node-properties/node-properties.component.html

Defect DS-691 fixed

---

src/app/home/control-panel/user/user.component.ts

Defect DS-713 fixed

---

src/app/home/b2b-flows-manage/node-properties/node-advanced-filter/node-advanced-filter.component.html
src/app/home/b2b-flows-manage/node-properties/node-advanced-filter/node-advanced-filter.component.ts

Defect DS-711 fixed

---

src/app/home/b2b-flows-manage/node-properties/node-properties.component.html

Defect DS-699 fixed

---

src/app/home/b2b-flows-manage/b2b-flow.service.ts
src/app/home/b2b-flows-manage/flow-node/flow-node.component.html
src/app/home/b2b-flows-manage/node-properties/connector-properties/connector-properties.component.html
src/app/home/b2b-flows-manage/node-properties/connector-properties/connector-properties.component.ts
src/app/home/b2b-flows-manage/node-properties/connector-properties/kafka-connector/kafka-connector.component.html
src/app/home/b2b-flows-manage/node-properties/connector-properties/kafka-connector/kafka-connector.component.ts
src/app/home/b2b-flows-manage/node-properties/node-properties.component.html
src/app/home/b2b-flows/b2b-flows.component.html
src/app/home/b2b-flows/b2b-flows.component.scss
src/app/home/b2b-flows/b2b-flows.component.ts

Kafka consumer and producer changes

---

src/app/home/b2b-flows-manage/b2b-flows-manage.component.ts
src/app/home/b2b-flows-manage/node-properties/node-properties.component.html
src/app/home/b2b-flows-manage/node-properties/node-properties.component.ts

Defect DS-695 fixed

---

src/app/home/b2b-flows-manage/node-properties/node-advanced-filter/node-advanced-filter.component.ts

Defect DS-705 fixed

---

src/app/home/b2b-flows-manage/b2b-flows-manage.component.ts

Defect DS-760 fixed

---

src/app/home/b2b-flows-manage/node-properties/node-advanced-filter/node-advanced-filter.component.html
src/app/home/b2b-flows-manage/node-properties/node-advanced-filter/node-advanced-filter.component.ts

Adding advanced filter - actual

---

src/app/home/b2b-flows-manage/b2b-flow.service.ts
src/app/home/b2b-flows-manage/node-properties/node-properties.component.html
src/app/home/b2b-flows-manage/node-properties/node-properties.component.scss
src/app/home/b2b-flows-manage/node-properties/node-properties.component.ts
src/app/home/b2b-flows/b2b-flows.component.ts
src/app/utils/styled-text/styled-text.component.html
src/app/utils/styled-text/styled-text.component.scss
src/assets/scss/bootstrap/_nav.scss

Additing conditions tab on nodes

---

src/app/home/b2b-flows-manage/node-properties/condition-properties/condition-properties.component.html

Prevent editing of name and condition of condition node in view mode

DS-728 - [B2B] Able to edit the conditons and name under the condition node in view mode

---

src/app/home/data-format-manage/data-format-manage.component.ts

On switch definition issue fix

---

src/app/home/b2b-flows-manage/b2b-flow.service.ts
src/app/home/data-format-manage/data-format-manage.component.html
src/app/home/data-format-manage/data-format-manage.component.ts
src/app/home/schema-utils/global-schema-structure.pipe.ts
src/app/home/schema-utils/schema-builder.service.ts
src/app/utils/structure-field-properties/date-property/date-property.component.html
src/app/utils/structure-field-properties/date-property/date-property.component.ts
src/app/utils/structure-field-properties/structure-field-properties.component.html
src/app/utils/structure-field-properties/structure-field-properties.component.ts

SFTP input/output changes

---

src/app/home/service-manager/service-manager.component.html
src/app/home/service-manager/service-manager.component.ts

Defect DS-658 fixed

---

src/app/home/local-bot/local-bot.component.ts

Defect DS-686 fixed

---

src/app/utils/styled-text/styled-text.component.html
src/app/utils/styled-text/styled-text.component.scss
src/app/utils/styled-text/styled-text.component.ts

Css changes on styled-text

---

src/app/utils/field-type/field-type-selector/field-type-selector.component.ts
src/app/utils/structure-field-properties/structure-field-properties.component.html
src/app/utils/structure-field-properties/structure-field-properties.component.ts
src/app/utils/structure-field/structure-field.component.ts

Change type issue fix on data formats

---

src/app/home/b2b-flows-manage/b2b-flows-manage.component.ts
src/app/utils/styled-text/styled-text.component.scss

Defect DS-789 fixed

---

src/app/home/b2b-flows-manage/node-properties/node-properties.component.html

Removing mandatory indicator

---

src/app/home/control-panel/user-group/user-group-manage/user-group-members/user-group-users/user-group-users.component.html
src/app/home/control-panel/user-group/user-group-manage/user-group-members/user-group-users/user-group-users.component.scss
src/app/home/service-manager/service-manager.component.html

Defect DS-791 fixed

---

src/app/home/b2b-flows-manage/node-properties/node-mapping/node-mapping.component.ts
src/app/home/schema-utils/manage-permissions/manage-permissions.component.ts

Defect DS-790 fixed

---

src/app/home/connectors-manage/connectors-manage.component.ts

Defect DS-794 fixed

---

src/app/home/b2b-flows-manage/node-properties/node-properties.component.html

Truncating ids and conditions

---

src/app/home/data-format-listing/data-format-listing.component.ts
src/app/home/data-format-manage/data-format-manage.component.ts
src/app/home/schema-utils/schema-builder.service.ts
src/app/home/service-manager/service-manager.component.html
src/app/home/service-manager/service-manager.component.scss
src/app/home/service-manager/service-manager.component.ts
src/app/utils/structure-field/structure-field.component.ts

Data format and service list changes

---

src/app/home/b2b-flows-manage/flow-node/flow-node.component.ts
src/app/home/b2b-flows-manage/node-properties/node-mapping/formula-editor/formula-editor.component.ts
src/app/home/b2b-flows-manage/node-properties/node-mapping/node-mapping.component.html
src/app/home/b2b-flows-manage/node-properties/node-mapping/node-mapping.component.ts

Double onSuccess path issue fix

---

package.json
src/environments/environment.prod.ts
src/environments/environment.ts

Clicking on a new formula now closes the previous one, preventing overlap.

DS-702 - [B2B] When a user clicks on the multiple attributes formula option, the formula screen overlaps

---

src/app/home/data-format-listing/data-format-listing.component.ts
src/app/home/schema-utils/schema-builder.service.ts
src/app/home/service-manager/service-manager.component.ts

Increasing description length

---

src/app/home/b2b-flows-manage/b2b-flow.service.ts
src/app/home/b2b-flows-manage/b2b-flows-manage.component.ts
src/app/home/b2b-flows-manage/node-properties/connector-properties/sftp-connector/sftp-connector.component.html
src/app/home/b2b-flows-manage/node-properties/node-properties.component.ts

SFTP issue fixes

---

src/app/home/b2b-flows-manage/node-properties/node-mapping/mapping-preset/mapping-preset.component.html

Defect DS-829 fixed

---

src/app/home/service-manager/service-manager.component.ts

Defect DS-828 fixed

---

src/app/home/b2b-flows-manage/node-properties/node-mapping/formula-editor/formula-editor.component.ts
src/app/home/b2b-flows-manage/node-properties/node-mapping/node-mapping.component.ts
src/app/home/b2b-flows/b2b-flows.component.html
src/app/home/b2b-flows/b2b-flows.component.scss

Advance mapping issue + Jerrys requests

---

src/app/home/b2b-flows-manage/node-properties/node-properties.component.ts

Defect DS-827 fixed

---

src/app/home/service-manager/service-manager.component.html
src/app/home/service-manager/service-manager.component.scss
src/app/home/service-manager/service-manager.component.ts

Step based service creation

---

src/app/home/b2b-flows-manage/node-properties/node-properties.component.ts

Changes requested by Sushmitha

---

src/app/react/reactflow/ReactFlowComponent.tsx
src/app/react/reactflow/reactflow.scss

Intersection node added

---

src/app/react/reactflow/custom-components/CustomErrorNode.tsx

Global error node name

---

src/app/home/b2b-flows-manage/b2b-flow.service.ts
src/app/react/reactflow/ReactFlowComponent.tsx
src/app/react/reactflow/custom-components/CustomNode.tsx
src/app/react/reactflow/reactflow.scss

Node focus issue fix

---

src/app/admin/env-variable-config/env-variable-config.component.html
src/app/admin/env-variable-config/env-variable-config.component.scss
src/app/admin/env-variable-config/env-variable-config.component.ts

Introduces
- Different tabs for Runtime and Installation variables
- Based on the selected user mode hide/show azure, ldap-related config variables 
Updated UI :

Enhance environment variables UI

---

src/app/login/login.component.html
src/app/login/login.component.ts

RH Azure login changes

---

src/app/login/login.component.html
src/app/login/login.component.ts

Azure login fix
